# This file was generated by GoReleaser. DO NOT EDIT.
class TelnyxMock < Formula
  desc "telnyx-mock is a mock HTTP server that responds like the real Telnyx API. It can be used instead of Telnyx's testmode to make test suites integrating with Telnyx faster and less brittle."
  homepage "https://github.com/team-telnyx/telnyx-mock"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/team-telnyx/telnyx-mock/releases/download/v0.1.0/telnyx-mock_0.1.0_darwin_amd64.tar.gz"
    sha256 "ebcb63bb6194264aa85da20e5c407828eb2e0824a435b928037462ab6221e330"
  elsif OS.linux?
    url "https://github.com/team-telnyx/telnyx-mock/releases/download/v0.1.0/telnyx-mock_0.1.0_linux_amd64.tar.gz"
    sha256 "097e4e0a2a342e873af3e4148334ca268ec526b5fc3f01899f7961bd7f5b4581"
  end

  def install
    bin.install "telnyx-mock"
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>KeepAlive</key>
    <dict>
      <key>SuccessfulExit</key>
      <false/>
    </dict>
    <key>Label</key>
    <string>#{plist_name}</string>
    <key>ProgramArguments</key>
    <array>
      <string>#{opt_bin}/telnyx-mock</string>
      <string>-http-port</string>
      <string>12111</string>
      <string>-https-port</string>
      <string>12112</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>WorkingDirectory</key>
    <string>#{var}</string>
    <key>StandardErrorPath</key>
    <string>#{var}/log/telnyx-mock.log</string>
    <key>StandardOutPath</key>
    <string>#{var}/log/telnyx-mock.log</string>
  </dict>
</plist>

  EOS
  end
end
